#ifndef SL_COMPONENT_CATALOG_H
#define SL_COMPONENT_CATALOG_H

// APIs present in project
#define SL_CATALOG_I2C_PRESENT
#define SL_CATALOG_I2C_I2C0_PRESENT
#define SL_CATALOG_I2S_PRESENT
#define SL_CATALOG_I2S_I2S0_PRESENT
#define SL_CATALOG_CMSIS_OS_COMMON_PRESENT
#define SL_CATALOG_EMLIB_CORE_PRESENT
#define SL_CATALOG_FREERTOS_KERNEL_PRESENT
#define SL_CATALOG_KERNEL_PRESENT
#define SL_CATALOG_SL_CORE_PRESENT
#define SL_CATALOG_SL_MAIN_PRESENT

#endif // SL_COMPONENT_CATALOG_H
